// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utisdawbzpwytgewfcur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0aXNkYXdienB3eXRnZXdmY3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzcxODksImV4cCI6MjA2OTI1MzE4OX0.A45f1THutXDsxA5pD0yS05MDbkhS0iBMuQHhYURspJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});